package com.bank.bian.procurement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Procurement
 *
 * Business Area:      Business Support
 * Business Domain:    Corporate Services
 * Functional Pattern: Process
 * Asset Type:         Purchase Order
 * Control Record:     Purchase Order Procedure
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Procurement — BIAN Semantic API")
                .description("Service Domain 'Procurement' (Process pattern) "
                        + "operating on the 'Purchase Order Procedure' control record.")
                .version("0.1.0"));
    }
}
